name: Guerillarobot.co
favicon: null
layout_spectrum: 0.42909
typography_spectrum: 0.21372
title: Guerillarobot.co
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11005355813540518
  lightness: 0.20210257777944207
  saturation: 0.666142525151372
  rhythmicContrast: 0.5182387770619243
purpose: []
