analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.20839
title: Guerillarobot.com
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.625
  brandStrength: 0.1875
  rhythmicContrast: 0.5
  brandColors:
    - '#000000'
    - '#fefdfb'
    - '#636363'
    - '#9d9d9d'
    - '#45bdd6'
  lightness: 0
purpose: []
favicon: null
name: Guerillarobot.com
typography_spectrum: 0.21372
