name: Guerillarobot.co
favicon: null
layout_spectrum: 0.42909
typography_spectrum: 0.21372
title: Guerillarobot.co
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefdfb'
    - '#636363'
    - '#9d9d9d'
    - '#45bdd6'
  brandStrength: 0.125
  lightness: 0
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
