title: Guerillarobot.com
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.625
  brandStrength: 0.1949517
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#FFC035'
    - '#020102'
    - '#A7ABAE'
    - '#1EA2F3'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Guerillarobot.com
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.21372
layout_spectrum: 0.20839
